# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: useHostedAgents
  displayName: Use Microsoft Hosted Agents?
  type: boolean
  default: false

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'

trigger: none

jobs:
  - job: buildAndPublish
    pool:
      ${{ if eq(parameters.useHostedAgents, false) }}:
        name: MyPools
      ${{ if eq(parameters.useHostedAgents, true) }}:
        vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        packageType: sdk
        version: '$(dotnetSdkVersion)'
    - task: Npm@1
      inputs:
        customCommand: 'install --save-dev'
    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'
    - ${{ if eq(agent.os, 'Windows_NT') }}:
      - script: 'node_modules\gulp\node_modules\.bin\gulp'
        displayName: 'gulp task'
    - ${{ if eq(agent.os, 'Linux') }}:
      - task: gulp@1
        displayName: 'gulp task'
    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - template: templates/build.yml
      parameters:
        buildConfiguration: 'Debub'
    - template: templates/build.yml
      parameters:
        buildConfiguration: 'Release'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeeded()