# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: pool
  displayName: hosted agents
  type: boolean
  default: false  
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-2019
  - ubuntu-latest
- name: agent
  displayName: My agent
  type: string
  default: Windows
  values:
    - Windows
    - Linux

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'

trigger: none

jobs:
- ${{ if not(eq(parameters.pool, true)) }}:
  - job: pool
    displayName: Self-hosted agents pool
    pool:
      name: MyPools
      demands:  
      - ${{ if eq(parameters.agent, 'Windows') }}:
        - agent.os -equals Windows_NT
      - ${{ if eq(parameters.agent, 'Linux') }}:
        - agent.os -equals Linux

    steps:
    - template: templates/set.yml
      parameters:
        - ${{ if eq(parameters.agent, 'Windows') }}:
          windows: true
        - ${{ if eq(parameters.agent, 'Linux') }}:
          windows: false

- ${{ if eq(parameters.pool, true) }}:
  - job: pool
    displayName: Hosted agents pool
    pool:
      vmImage: ${{ parameters.image }}
      demands:  
      - npm

    steps:
    - template: templates/set.yml
      parameters:
        windows: false