# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: pool
  displayName: hosted agents
  type: boolean
  default: false  
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-2019
  - ubuntu-latest
- name: agent
  displayName: My agent
  type: string
  default: ALAVADENZM-DH01
  values:
    - ALAVADENZM-DH01
    - adriana-VirtualBox

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'

trigger: none

jobs:
- ${{ if not(eq(parameters.pool, true)) }}:
  - template: templates/start.yml
    parameters:
      agent: ${{ parameters.agent }}

- ${{ if eq(parameters.pool, true) }}:
  - template: templates/start-ha.yml
    parameters:
      image: ${{ parameters.image }}