# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: pool
  displayName: hosted agents
  type: boolean
  default: false  

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'

trigger: none

steps:
- ${{ if not(eq(parameters.pool, true)) }}:
  - template: templates/start.yml

- ${{ if eq(parameters.pool, true) }}:
  - template: templates/start-ha.yml

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debub'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()