parameters:
- name: agent
  displayName: My agent
  type: string
  default: ALAVADENZM-DH01
  values:
    - ALAVADENZM-DH01
    - adriana-VirtualBox

jobs:
- job: build
  displayName: Self-hosted agents
  pool:
	name: MyPools
	demands:  
	- ${{ if eq(parameters.agent, 'ALAVADENZM-DH01') }}:
		- name -equals myhost


  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK $(dotnetSdkVersion)'
    inputs:
  	packageType: sdk
  	version: '$(dotnetSdkVersion)'
  - task: Npm@1
    inputs:
  	customCommand: 'install --save-dev'
  - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
    displayName: 'Compile Sass assets'
  - ${{ if eq(parameters.agent, 'ALAVADENZM-DH01') }}:
  	- script: 'node_modules\gulp\node_modules\.bin\gulp'
  	  displayName: 'gulp task'
  - ${{ if not(eq(parameters.agent, 'ALAVADENZM-DH01')) }}:
  	- task: gulp@1
  	  displayName: 'gulp task'
  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build info'
    workingDirectory: $(wwwrootDir)
  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
  	command: 'restore'
  	projects: '**/*.csproj'
  - template: build.yml
    parameters:
  	buildConfiguration: 'Debub'
  - template: build.yml
    parameters:
  	buildConfiguration: 'Release'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeeded()